**Retrieving data> Google Drive**

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive') 
%cd gdrive/ 
%cd MyDrive

In [10]:
import pandas as pd
import numpy as np 
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.cluster import KMeans
df= pd.read_csv('BigBlue.csv') 
df.head()

   EmployeeID  UsageRate  Recognition  Leader
0           1   0.000000            0       0
1           2   0.632785            0       0
2           3   0.003499            0       0
3           4   0.000234            0       0
4           5   0.000438            0       0

Droping the varible, xxx,  which is not helpfull for the clustering!

In [11]:
df_feature= df.drop(['xxx'], axis=1)
df_feature.head()

   UsageRate  Recognition  Leader
0   0.000000            0       0
1   0.632785            0       0
2   0.003499            0       0
3   0.000234            0       0
4   0.000438            0       0

**You may first explore the basic feature of the dataset!**

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   107 non-null    int64
 1   UsageRate    107 non-null    float64
 2   Recognition  107 non-null    int64
 3   Leader       107 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 3.5 KB

You may use silhouette_score for finding the optimum number of clusters!

In [81]:
silh=[]
silh = [0 for i in range(10)] 

y= range(2,10)
for n in y:
 kmeans = KMeans(n_clusters=n).fit(df_feature)
 silh[n] = silhouette_score(df_feature, kmeans.labels_)
print(silh)
np.argmax(silh)

[0, 0, 0.7976437985621966, 0.7584700782168847, 0.7365283751562927, 0.6927570542935766, 0.7145760681923415, 0.7230746292996605, 0.7219725652434207, 0.7261659938204714]

2

you can use below code to see the cluster centers, I did for the case when you decide the value of 4 as number of clusters

In [82]:
kmeans = KMeans(n_clusters=4).fit(df_feature)
kmeans.cluster_centers_

array([[ 2.01891032e-01, -2.77555756e-16,  1.24900090e-16],
       [ 7.52834313e-01,  2.50000000e+00,  0.00000000e+00],
       [ 7.41602763e-01,  1.00000000e+00,  6.93889390e-18],
       [ 8.11252052e-01,  2.75000000e+00,  1.50000000e+00]])

In [91]:
np.around(kmeans.cluster_centers_, decimals=6)

array([[ 0.201891, -0.      ,  0.      ],
       [ 0.752834,  2.5     ,  0.      ],
       [ 0.741603,  1.      ,  0.      ],
       [ 0.811252,  2.75    ,  1.5     ]])